# Promise详解



[TOC]

### Promise的声明

promise的声明:

```js
new Promise((resolve,reject)=>{
})
```

在Promise中传入一个函数，其中两个参数为`resolve(成功)和reject(失败)`，这个函数名字叫做`executor`

```js
  // Promise类定义
    new Promise(
      //构造函数，传入executor
      constructor(executor){
        //成功
        let resolve=()=>{}
        //失败
        let reject=()=>{}
        //立即执行
        executor(resolve,reject)
      }
    )
```

### Promise的三种状态

promise有三种状态`pending,fulfilled,rejected`

其中`pending`表示等待状态

`fulfilled`表示任务完成成功状态

`rejected`表示任务失败状态

状态的转换可以是`pending->fulfilled`或者`pending->rejected`

成功`fulfilled`时不可以转变为其他状态，并且必须有一个不可改变的`value`值

失败`rejected`时也不可以转变为其他状态，并且必须有一个不可以改变的`reason`原因

```js
//成功时转换状态从pending到fulfilled,接收结果参数value
new Promise((resolve,rejected)=>{resolve(value)})
//失败时转换状态从pending到rejected,接收原因参数reason
new Promise((resolve,rejected)=>{rejected(reason)})
//其中状态和参数都不可以改变
//如果executor报错的话直接状态变为rejected
```

所以具体Promise类的实现为：

```js
 //promise的完整类实现
    class Promise {
      //构造函数
      constructor(executor) {
        //初始化状态为pending
        this.state = "pending";
        //成功的值和失败的原因定义为undefined
        this.value = undefined;
        this.reason = undefined;

        //成功的返回
        let resolve = (value) => {
          if (this.state == "pending") {
            //如果此时的状态为等待，就改变成成功状态fulfilled
            this.state == "fulfilled";
            //存储传入value的值
            this.value = value;
          }
        };

        //失败的返回
        let reject = (reason) => {
          if (this.state == "pending") {
            //如果此时的状态为等待状态，则改变状态为失败
            this.state = "rejected";
            //失败的值reason存储传入的reason
            this.reason = reason;
          }
        };

        //如果构造函数报错。直接返回rejected
        try{
          executor(resolve,reject)
        }catch(err){
          reject(err)//直接把捕获到的错误传入reject
        }
      }
    }
```

### `then()`

promise中具有一个`then(onFulfilled,onRejected)`函数，当状态为`rejected`时调用`onRejected`函数，传入参数`this.reason`，当状态为`fulfilled`时调用`onfulfilled`函数,传入参数`this.value`

`onFulfilled`,`onRejected`如果他们是函数，则必须分别在`fulfilled`，`rejected`后被调用，`value`或`reason`依次作为他们的第一个参数

```js
      then(onFulfilled,onRejected){
        if(this.status=='fulfilled'){
          //如果当前状态为fulfilled,调用onFulfilled传入value
          onFulfilled(this.value)
        }else if(this.status=='rejected'){
          //如果当前状态为rejected,调用onRejected传入reason
          onRejected(this.reason)
        }
      }
```

### 完全体Promise类的实现

```js
 //promise的完整类实现
    class Promise {
      //构造函数
      constructor(executor) {
        //初始化状态为pending
        this.status = "pending";
        //成功的值和失败的原因定义为undefined
        this.value = undefined;
        this.reason = undefined;

        //成功的返回
        let resolve = (value) => {
          if (this.status == "pending") {
            //如果此时的状态为等待，就改变成成功状态fulfilled
            this.status == "fulfilled";
            //存储传入value的值
            this.value = value;
          }
        };

        //失败的返回
        let reject = (reason) => {
          if (this.status == "pending") {
            //如果此时的状态为等待状态，则改变状态为失败
            this.status = "rejected";
            //失败的值reason存储传入的reason
            this.reason = reason;
          }
        };

        //如果构造函数报错。直接返回rejected
        try{
          executor(resolve,reject)
        }catch(err){
          reject(err)//直接把捕获到的错误传入reject
        }
      }

      then(onFulfilled,onRejected){
        if(this.status=='fulfilled'){
          //如果当前状态为fulfilled,调用onFulfilled传入value
          onFulfilled(this.value)
        }else if(this.status=='rejected'){
          //如果当前状态为rejected,调用onRejected传入reason
          onRejected(this.reason)
        }
      }
    }
```

### 解决异步的实现

**现在基本可以实现简单的同步代码，但是当resolve在setTomeout内执行，then时state还是pending等待状态 我们就需要在then调用的时候，将成功和失败存到各自的数组，一旦reject或者resolve，就调用它们**

类似于发布订阅，先将then里面的两个函数储存起来，由于一个promise可以有多个then，所以存在同一个数组内。

```js
//多个then
let promise=new Promise()
p.then()
p.then()
```

